repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
    -   id: black

- repo: https://github.com/gitleaks/gitleaks
  rev: v8.23.3
  hooks:
    - id: gitleaks

# - repo: https://github.com/ansible/ansible-lint
#   rev: v6.22.1  # Replace with the latest version of ansible-lint
#   hooks:
#     - id: ansible-lint
#       args: [--config=.ansible-lint]